[package]
name = "funky_lesson_core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
reqwest = { version = "0.12.9", features = ["rustls-tls","json", "cookies"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aes = "0.8.4"
ecb = "0.1.2"
block-modes = "0.9.1"
base64-simd = "0.8.0"
futures = "0.3.31"